server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=organizaciones-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/organizaciones/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter 

spring.cloud.gateway.routes[1].id=coincidencias-service
spring.cloud.gateway.routes[1].uri=http://localhost:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/coincidencias/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter 

jwt.secret=sanosysalvos1234

# rutas 9 microservicios