server.port=${PORT:8080}
spring.application.name=api-gateway

jwt.secret=${JWT_SECRET:sanosysalvos1234}

spring.cloud.gateway.routes[0].id=sanosysalvos-bff
spring.cloud.gateway.routes[0].uri=http://${BFF_HOST:localhost}:${BFF_PORT:8083}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[0].filters[1]=name=CircuitBreaker,args.name=bffCircuitBreaker

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins[0]=${FRONT_URL:http://localhost:3000}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders[0]=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.discovery.locator.enabled=false