server.port=8080
spring.application.name=api-gateway
jwt.secret=sanosysalvos1234

spring.cloud.gateway.routes[0].id=sanosysalvos-bff
spring.cloud.gateway.routes[0].uri=http://${BFF_HOST:localhost}:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[0].filters[1]=name=CircuitBreaker,args.name=bffCircuitBreaker

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.discovery.locator.enabled=false